kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-beegfs-provisioner
spec:
  serviceName: "csi-beegfs-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-beegfs-provisioner
  template:
    metadata:
      labels:
        app: csi-beegfs-provisioner
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-beegfsplugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-beegfs
            type: DirectoryOrCreate
          name: socket-dir
